### ISSUE TITLE
Autocommit might not correctly deal with unset PKs

### ISSUE THREAD

**Issue by null-directory** [CorsoSource/plastic#3]
There's an error when instantiating objects when giving initial values that are not the PK. If the PK is also _not_ autogenerated, then the engine really should just fail the insert since it needs the value yet it isn't set.

At the _very_ least the error should be less nonsensical than the current stack trace.

## Example info:

From @kylechase: the following fails
```
from plastic.connectors.ignition import connect_table

# Connect to table
table = connect_table(
	db = 'scorekeeper',
	schema = "scorekeeper",
	table = 'players',
	autocommit = True
)

event = table(fname="Test",lname="Testerson")
```

https://gist.github.com/kylechase/d1651d01229a1f2139da4578ed3afc02

using the following table schema:
```sql
CREATE TABLE IF NOT EXISTS `players` (
  `id_player` char(5) NOT NULL,
  `fname` varchar(50) DEFAULT NULL,
  `lname` varchar(50) DEFAULT NULL,
  `bats` char(1) DEFAULT NULL,
  `throws` char(1) DEFAULT NULL,
  PRIMARY KEY (`id_player`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
```

**Comment by null-directory** [comment]
On my localhost:
```python
from shared.tools.pretty import p,pdir,install;install()
from plastic.connectors.ignition import connect_table, PlasticIgnition
Players = connect_table(
	'MariaDB', 'scorekeeper', 'players',
		autocommit = True
)
p1 = Players(fname='AAAA', lname='ZZZZ', bats='L')
```
where in the stacktrace the key clue is in `[L, AAAA, ZZZZ, <'scorekeeper.players' column: id_player>]` - it tried to set the PK to the meta column instance instead of a real value. Needs fixin' or an error.

and here's the stacktrace in all it's horrific mess
```java
Java Traceback:
Traceback (most recent call last):
  File "<input>", line 13, in <module>
  File "<module:plastic.core>", line 68, in resumeAfter
  File "<module:plastic.core>", line 124, in __setattr__
  File "<module:plastic.core>", line 392, in _commit
  File "<module:plastic.core>", line 321, in _update
  File "<module:plastic.connectors.base>", line 128, in update
  File "<module:plastic.connectors.ignition>", line 80, in _execute_update
-- Update from PlasticORM_Connection
update scorekeeper.players
set bats=?,fname=?,lname=?
where id_player=?
, [L, AAAA, ZZZZ, <'scorekeeper.players' column: id_player>], Transaction datasource 'MariaDB', 834a1ce7-996b-4ee9-a276-29e693e9bf79, false, false)
	at com.inductiveautomation.ignition.common.script.builtin.AbstractDBUtilities.error(AbstractDBUtilities.java:392)
	at com.inductiveautomation.ignition.common.script.builtin.AbstractDBUtilities.runPrepUpdate(AbstractDBUtilities.java:268)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
java.lang.Exception: java.lang.Exception: Error executing system.db.runPrepUpdate(
-- Update from PlasticORM_Connection
update scorekeeper.players
set bats=?,fname=?,lname=?
where id_player=?
, [L, AAAA, ZZZZ, <'scorekeeper.players' column: id_player>], Transaction datasource 'MariaDB', 834a1ce7-996b-4ee9-a276-29e693e9bf79, false, false)

	at org.python.core.PyException.doRaise(PyException.java:211)
	at org.python.core.Py.makeException(Py.java:1638)
	at org.python.core.Py.makeException(Py.java:1642)
	at org.python.core.Py.makeException(Py.java:1646)
	at org.python.core.Py.makeException(Py.java:1650)
	at org.python.pycode._pyx154._update$24(<module:plastic.core>:324)
	at org.python.pycode._pyx154.call_function(<module:plastic.core>)
	at org.python.core.PyTableCode.call(PyTableCode.java:173)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:134)
	at org.python.core.PyFunction.__call__(PyFunction.java:416)
	at org.python.core.PyMethod.__call__(PyMethod.java:126)
	at org.python.pycode._pyx154._commit$28(<module:plastic.core>:392)
	at org.python.pycode._pyx154.call_function(<module:plastic.core>)
	at org.python.core.PyTableCode.call(PyTableCode.java:173)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:134)
	at org.python.core.PyFunction.__call__(PyFunction.java:416)
	at org.python.core.PyMethod.__call__(PyMethod.java:126)
	at org.python.pycode._pyx154.__setattr__$7(<module:plastic.core>:124)
	at org.python.pycode._pyx154.call_function(<module:plastic.core>)
	at org.python.core.PyTableCode.call(PyTableCode.java:173)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:168)
	at org.python.core.PyFunction.__call__(PyFunction.java:437)
	at org.python.core.PyMethod.__call__(PyMethod.java:156)
	at org.python.core.PyMethod.__call__(PyMethod.java:147)
	at org.python.core.PyObjectDerived.__setattr__(PyObjectDerived.java:1043)
	at org.python.pycode._pyx154.resumeAfter$3(<module:plastic.core>:68)
	at org.python.pycode._pyx154.call_function(<module:plastic.core>)
	at org.python.core.PyTableCode.call(PyTableCode.java:173)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:306)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:197)
	at org.python.core.PyFunction.__call__(PyFunction.java:485)
	at org.python.core.PyMethod.instancemethod___call__(PyMethod.java:237)
	at org.python.core.PyMethod.__call__(PyMethod.java:228)
	at org.python.core.PyMethod.__call__(PyMethod.java:223)
	at org.python.core.Deriveds.dispatch__init__(Deriveds.java:20)
	at org.python.core.PyObjectDerived.dispatch__init__(PyObjectDerived.java:1112)
	at org.python.core.PyType.type___call__(PyType.java:2408)
	at org.python.core.PyType$type___call___exposer.__call__(Unknown Source)
	at org.python.core.PyTypeDerived.__call__(PyTypeDerived.java:1003)
	at org.python.core.PyObject.__call__(PyObject.java:400)
	at org.python.pycode._pyx146.f$0(<input>:13)
	at org.python.pycode._pyx146.call_function(<input>)
	at org.python.core.PyTableCode.call(PyTableCode.java:173)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.Py.runCode(Py.java:1687)
	at org.python.core.Py.exec(Py.java:1731)
	at org.python.util.PythonInterpreter.exec(PythonInterpreter.java:277)
	at org.python.util.InteractiveInterpreter.runcode(InteractiveInterpreter.java:130)
	at com.inductiveautomation.ignition.designer.gui.tools.jythonconsole.JythonConsole$ConsoleWorker.doInBackground(JythonConsole.java:626)
	at com.inductiveautomation.ignition.designer.gui.tools.jythonconsole.JythonConsole$ConsoleWorker.doInBackground(JythonConsole.java:614)
	at java.desktop/javax.swing.SwingWorker$1.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.desktop/javax.swing.SwingWorker.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Traceback (most recent call last):
  File "<input>", line 13, in <module>
  File "<module:plastic.core>", line 68, in resumeAfter
  File "<module:plastic.core>", line 124, in __setattr__
  File "<module:plastic.core>", line 392, in _commit
  File "<module:plastic.core>", line 321, in _update
  File "<module:plastic.connectors.base>", line 128, in update
  File "<module:plastic.connectors.ignition>", line 80, in _execute_update
-- Update from PlasticORM_Connection
update scorekeeper.players
set bats=?,fname=?,lname=?
where id_player=?
, [L, AAAA, ZZZZ, <'scorekeeper.players' column: id_player>], Transaction datasource 'MariaDB', 834a1ce7-996b-4ee9-a276-29e693e9bf79, false, false)
	at com.inductiveautomation.ignition.common.script.builtin.AbstractDBUtilities.error(AbstractDBUtilities.java:392)
	at com.inductiveautomation.ignition.common.script.builtin.AbstractDBUtilities.runPrepUpdate(AbstractDBUtilities.java:268)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
java.lang.Exception: java.lang.Exception: Error executing system.db.runPrepUpdate(
-- Update from PlasticORM_Connection
update scorekeeper.players
set bats=?,fname=?,lname=?
where id_player=?
, [L, AAAA, ZZZZ, <'scorekeeper.players' column: id_player>], Transaction datasource 'MariaDB', 834a1ce7-996b-4ee9-a276-29e693e9bf79, false, false)
```

**Comment by null-directory** [comment]
I've added the option to add a default function. Eventually we'll have Plastic pull True/False for if a column has a default value, but not right away (I'm fairly certainl each database engine has their own special and _quirky_ way of telling how defaults work).

So this at least lets a default get set. In the given example above, a `lambda` is provided that simply generates a value.

```python
from shared.tools.pretty import p,pdir,install;install()

from plastic.connectors.ignition import connect_table, PlasticIgnition

import string, random

def random_letters(n):
	return ''.join(random.choice(string.letters) for _ in range(n))

Players = connect_table(
	'MariaDB', 'scorekeeper', 'players',
	column_defaults = {
		'id_player': lambda: random_letters(5)
	},
	autocommit = True
)

p1 = Players(fname='AAAA', lname='ZZZZ', bats='L')
```

![image](https://github.com/CorsoSource/plastic/assets/11398106/73f82e08-030a-4216-bf5b-ceae466b8300)

**Comment by null-directory** [comment]
This was a minor can of worms. But if you don't use autocommit, there's a whole host of confusion if defaults aren't properly propagated automagically.

So here's an example using the initial case given. It shows that a default function can be set after the fact and how values can be lazily set after the fact.

```python
from shared.tools.pretty import p,pdir,install;install()

from plastic.tools import *

import string, random

def random_letters(n):
	return ''.join(random.choice(string.letters) for _ in range(n))



Players = connect_table(
	'MariaDB', 'scorekeeper', 'players',
	column_defaults = {
		'id_player': lambda: random_letters(5)
	},
)

Teams = connect_table('MariaDB', 'scorekeeper', 'teams',)
Teams.id_team.default = lambda: random_letters(5)


Rosters = connect_table('MariaDB', 'scorekeeper', 'rosters',)

p1 = Players(fname='John', lname='Doe')
p1.bats, p1.throws = 'L', 'R'

t1 = Teams(org='Sports Org', name='Orangers')
t1.short_name = 'O'

r1 = Rosters()
r1.id_team = t1.id_team
r1.id_player = p1.id_player

print p1.id_player
print r1.id_player

newly_generated_id = p1.id_player.default

print r1.id_player
```
which yields
```python
Jython 2.7.2 (uncontrolled:000000000000, Jan 25 2022, 14:39:15)
[OpenJDK 64-Bit Server VM (Azul Systems, Inc.)] on java11.0.18

>>> 
<unset: id_player>
<unset: id_player>
WIaXr
>>> 
<unset: id_player>
<unset: id_player>
RBZyf
>>> 
```
![image](https://github.com/CorsoSource/plastic/assets/11398106/168f431a-8f7c-4a50-a1ac-fa158a61cb06)

**Comment by null-directory** [comment]
Continuing, this tests the `commit` function added as a QoL bit
```python
from shared.tools.pretty import p,pdir,install;install()

from plastic.tools import *

import string, random

def random_letters(n):
	return ''.join(random.choice(string.letters) for _ in range(n))



Players = connect_table(
	'MariaDB', 'scorekeeper', 'players',
	column_defaults = {
		'id_player': lambda: random_letters(5)
	},
)

Teams = connect_table(
	'MariaDB', 'scorekeeper', 'teams',
)
Teams.id_team.default = lambda: random_letters(5)


Rosters = connect_table(
	'MariaDB', 'scorekeeper', 'rosters',
)


p1 = Players(fname='John', lname='Doe')
p1.bats, p1.throws = 'L', 'R'


t1 = Teams(org='Sports Org', name='Orangers')
t1.short_name = 'O'

r1 = Rosters()
r1.id_team = t1.id_team
r1.id_player = p1.id_player

print repr(r1)

for Table in (Players, Teams, Rosters):
	commit(Table)


rr1 = Rosters(
		id_team=t1.id_team,
		id_player=p1.id_player
	)

print repr(rr1)
```
which correctly yields the following
```python
Jython 2.7.2 (uncontrolled:000000000000, Jan 25 2022, 14:39:15)
[OpenJDK 64-Bit Server VM (Azul Systems, Inc.)] on java11.0.18

>>> 
<scorekeeper.rosters (
	  id_team = <unset: id_team>
	, id_player = <unset: id_player>
	, number = <unset: number>
	, status = <unset: status>)>
<scorekeeper.rosters (
	  id_team = 'sIANC'
	, id_player = 'fkQdZ'
	, number = None
	, status = True)>
>>> 
```

Note that the original has an unset `status`, but the newly retrieved `rr1` has that set to `True` since that's what the database has as a default for that column. Also note that it's `None` for `number` since that's not unset: the database has not value for that, which may be correct.

Might make a change later that sets all `NULL` values to a `PlasticColumnBackreference` so that these can be referenced more easily.

**Comment by null-directory** [comment]
@kylechase Here's the current build from this branch.
This won't address weird column serialization things that _might_ be the result of type weirdness, but it should at least make it obvious when it's not loading correctly.
[plastic_v1.1.0.zip](https://github.com/CorsoSource/plastic/files/13191296/plastic_v1.1.0.zip)
